# Generated by Django 2.1.3 on 2019-01-16 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='workflowlevel2_uuid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, help_text='List of WorkflowLevel2s', null=True, size=None),
        ),
    ]
