# Generated by Django 2.1.3 on 2019-01-16 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_siteprofile_workflowlevel2_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
