# Generated by Django 2.1.3 on 2019-04-01 13:45

import django.contrib.postgres.indexes
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20190121_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletype',
            name='organization_uuid',
            field=models.UUIDField(db_index=True, verbose_name='Organization UUID'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='organization_uuid',
            field=models.UUIDField(db_index=True, verbose_name='Organization UUID'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='siteprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['workflowlevel2_uuid'], name='location_si_workflo_768d25_gin'),
        ),
    ]
