# Generated by Django 2.1.3 on 2019-04-08 12:41

from decimal import Decimal
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20190401_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=Decimal('0.00'), help_text='Latitude (Decimal Coordinates)', max_digits=25),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=Decimal('0.00'), help_text='Longitude (Decimal Coordinates)', max_digits=25),
        ),
    ]
