# Generated by Django 2.1.3 on 2019-04-08 13:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20190408_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
