# Generated by Django 2.1.9 on 2019-06-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20190605_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='is_global',
            field=models.BooleanField(default=False, help_text='All organizations have access to global ProfileTypes.'),
        ),
    ]
