services:
  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db

pipeline:
  test:
    image: python:3.6
    commands:
      - bash scripts/wait-for-it.sh $${DATABASE_HOST}:$${DATABASE_PORT} -t 45
      - bash scripts/run-tests.sh --ci
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - SECRET_KEY=nothing
    when:
      event: [pull_request, push, tag]

  build-docker-image-tag:
    image: plugins/docker
    registry:
      from_secret: DOCKER_REGISTRY
    repo:
      from_secret: DOCKER_REPO
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    auto_tag: true
    insecure: true
    file: Dockerfile
    when:
      event: [tag]
      branch: [master]
      status: [success]

  prebuild-docker-static-image:
    image: python:3.6
    commands:
      - bash scripts/run-collectstatic.sh
    when:
      event: [tag]
      status: [success]

  build-docker-static-image-tag:
    image: plugins/docker
    insecure: true
    registry:
      from_secret: DOCKER_REGISTRY
    repo:
      from_secret: DOCKER_REPO_STATIC
    dockerfile: Dockerfile.nginx
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    when:
      event: [tag]
      status: [success]
